name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ANDROID_PAT }}


      # Setup JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      # Gradle Cache
      - name: Gradle Cache
        uses: ./.github/actions/gradle-cache
        with:
          key-prefix: gradle-build

      # Grant permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Upload APK artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
