name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - "release/*"
      - "develop"
      - "master"

jobs:
  checks:
    name: Build & Static Checks
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ANDROID_PAT }}

      # Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Gradle
      - name: Gradle Cache
        uses: ./.github/actions/gradle-cache
        with:
          key-prefix: gradle-checks

      # Permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Run Lint
      - name: Run Android Lint
        run: ./gradlew lintDebug

      # Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Run Detekt
      - name: Run Detekt
        run: ./gradlew detekt

      # Upload Reports (backup artifacts)
      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

      - name: Upload Detekt Report
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: app/build/reports/detekt/detekt.html

  danger:
    runs-on: ubuntu-latest
    name: "PR Sanity Check"
    if: contains(github.head_ref,'renovate') == false
    steps:
      - uses: actions/checkout@v4
      - name: Danger
        uses: danger/kotlin@1.3.3
        with:
          args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.ANDROID_PAT }}
