name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    name: PR Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ANDROID_PAT }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Gradle Cache
        uses: ./.github/actions/gradle-cache
        with:
          key-prefix: gradle-lint

      - name: change wrapper permission
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      # ✅ NEW: Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # ✅ NEW: Upload APK
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
